# Generated by Django 4.0.5 on 2022-07-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
